apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-scheduler
spec:
  selector:
    matchLabels:
      app: flask-scheduler
  template:
    metadata:
      labels:
        app: flask-scheduler
    spec:
      containers:
      - name: flask-scheduler
        image: sha256:ebbac58692666dafd5620474f6186a139b943963693719384a78c3b7edf9a30f/flask-scheduler
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: flask-scheduler
spec:
  selector:
    app: flask-scheduler
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001