version: '3'

services:
  app1:
    build:
      context: ./api_request
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    restart: unless-stopped

  app2:
    build:
      context: ./api_scheduler
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped