apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dual-port-route
spec:
  port:
    targetPort: 5000
  alternateBackends:
    - kind: Service
      name: my-service
      port:
        targetPort: 8080
  to:
    kind: Service
    name: my-service
  tls:
    termination: edge
  wildcardPolicy: None