apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  selector:
    app: my-app
  ports:
    - name: api1-port
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: api2-port
      protocol: TCP
      port: 8080
      targetPort: 8000
  type: ClusterIP