apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: flask-app
    spec:
      lookupPolicy:
        local: true
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: flask-app
    spec:
      source:
        type: Git
        git:
          uri: https://github.com/your-repo/flask-app.git # replace with your own repository URL
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: flask-app:latest
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: flask-app
    spec:
      replicas: 1
      selector:
        app: flask-app
      template:
        metadata:
          labels:
            app: flask-app
        spec:
          containers:
            - name: flask-app
              image: flask-app:latest
              ports:
                - containerPort: 5000
                  protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      name: flask-app
    spec:
      ports:
        - name: http
          port: 80
          targetPort: 5000
      selector:
        app: flask-app
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: flask-app-route
    spec:
      host: flask-app.example.com # replace with your own domain name or leave blank for auto-generated one
      to:
        kind: Service
        name: flask-app

