apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: flask-api:latest
          ports:
            - containerPort: 5000