apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-api-build
  labels:
    BuildConfig: flask-api-build
spec:
  source:
    contextDir: /
    git:
      uri: https://github.com/Minh-Triet/dual_api.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: 'flask-api:latest'
  triggers:
    - type: ConfigChange