apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-api-build
spec:
  source:
    contextDir: api/
    git:
      uri: https://github.com/Minh-Triet/dual_api.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: python:3.9
      dockerfilePath: Dockerfile
      forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: flask-api:latest
  triggers:
    - type: ConfigChange
  runPolicy: Serial