apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: image-registry.openshift-image-registry.svc:5000/minh-triet-dev/app-api:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flask-api-route
spec:
  to:
    kind: Service
    name: flask-api-service
  port:
    targetPort: 80
