apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-scheduler-build
spec:
  source:
    contextDir: scheduler/
    git:
      uri: https://github.com/Minh-Triet/dual_api.git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'flask-scheduler:latest'
  triggers:
    - type: ConfigChange