apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: flask-scheduler
spec:
  replicas: 1
  selector:
    app: flask-scheduler
  template:
    metadata:
      labels:
        app: flask-scheduler
    spec:
      containers:
        - name: flask-scheduler
          image: flask-scheduler:latest
          ports:
            - containerPort: 8080