apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-scheduler-build
spec:
  source:
    contextDir: scheduler/
    git:
      uri: https://github.com/Minh-Triet/dual_api.git
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: python:3.8
      env:
        - name: APP_ROOT
          value: scheduler
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: flask-scheduler:latest
  triggers:
    - type: ConfigChange